excluded:
- Pods

disabled_rules:
- trailing_whitespace
- force_cast
- identifier_name
- function_parameter_count
- nesting
- weak_delegate
- type_name
- type_body_length
- legacy_hashing

line_length:
  warning: 400
  error: 500
file_length:
  warning: 400
  error: 800
function_body_length:
  warning: 60
  error: 120
cyclomatic_complexity:
  warning: 10
  error: 15

warning_threshold: 20

reporter: "xcode"